### ISSUE TITLE
Configure dockerfile and docker-compose for react app

### ISSUE THREAD

**Issue by mstrluke** [DvLuke/nextjs-redux-todoapp#1]
It is necessary to configure the launch of the react app in the development and production environment via Dockerfile and docker-compose.yml

node version is 12.18.2

**Comment by Zoxon470** [comment]
@DvLuke I want to get this issue.

**Comment by mstrluke** [comment]
@Zoxon470 Ok, take it, I will assign to you.

**Comment by Zoxon470** [comment]
@DvLuke Can you check my pull request? https://github.com/DvLuke/nextjs-redux-todoapp/pull/2

**Comment by mstrluke** [comment]
@Zoxon470 Hello, you are good, thanks!
